
export const dashboardData = [
  {
    id: 1,
    number: "01",
    code: "6465",
    name: "soibi marks",
    email: "soibi@naebidynamic.com",
    details: "Details",
  },
  {
    id: 2,
    number: "02",
    code: "5665",
    name: "Henry Nwosu",
    email: "Hnwosu@naebidynamic.com",
    details: "Details",
  },
  {
    id: 3,
    number: "03",
    code: "1785",
    name: "Ovunda Tom",
    email: "tovunda@naebidynamic.com",
    details: "Details",
  },
]

export const companiesData = [
  {
    id: 1,
    number: "01",
    code: "6465",
    name: "Bell Oil and Gas",
    category: "Drilling and well services",
    details: "Details",
  },
  {
    id: 2,
    number: "02",
    code: "5665",
    name: "NIPCO PLC",
    category: "Drilling and well services",
    details: "Details",
  },
  {
    id: 3,
    number: "03",
    code: "1785",
    name: "NIGERIA LNG",
    category: "Drilling and well services",
    details: "Details",
  },
  {
    id: 4,
    number: "04",
    code: "6465",
    name: "FRONTIER OIL LIMITED",
    category: "Drilling and well services",
    details: "Details",
  },
  {
    id: 5,
    number: "05",
    code: "5665",
    name: "ALFRED PETERSON *",
    category: "Drilling and well services",
    details: "Details",
  },
  {
    id: 6,
    number: "06",
    code: "1755",
    name: "MARVEL LIMITED",
    category: "Drilling and well services",
    details: "Details",
  },
  {
    id: 7,
    number: "07",
    code: "6465",
    name: "ZUKUS INDUSTRIES",
    category: "Drilling and well services",
    details: "Details",
  },
  {
    id: 8,
    number: "08",
    code: "5665",
    name: "NESTOIL LIMITED",
    category: "Drilling and well services",
    details: "Details",
  },
  {
    id: 9,
    number: "09",
    code: "1755",
    name: "LEKOIL LIMITED",
    category: "Drilling and well services",
    details: "Details",
  },
];


export const airlineData = [
  {
    id: 1,
    number: "01",
    code: "6465",
    name: "Samap Travels & Tours Ltd",
    category: "1 Month Ago",
    details: "Details",
  },
  {
    id: 2,
    number: "02",
    code: "5665",
    name: "Nesto Aviation Services Ltd",
    category: "Drilling and well services",
    details: "Details",
  },
  {
    id: 3,
    number: "03",
    code: "1785",
    name: "OAS Helicopters",
    category: "Drilling and well services",
    details: "Details",
  },
  {
    id: 4,
    number: "04",
    code: "6465",
    name: "FRONTIER OIL LIMITED",
    category: "Drilling and well services",
    details: "Details",
  },
  {
    id: 5,
    number: "05",
    code: "5665",
    name: "ALFRED PETERSON *",
    category: "Drilling and well services",
    details: "Details",
  },
  {
    id: 6,
    number: "06",
    code: "1755",
    name: "MARVEL LIMITED",
    category: "Drilling and well services",
    details: "Details",
  },
  {
    id: 7,
    number: "07",
    code: "6465",
    name: "ZUKUS INDUSTRIES",
    category: "Drilling and well services",
    details: "Details",
  },
  {
    id: 8,
    number: "08",
    code: "5665",
    name: "NESTOIL LIMITED",
    category: "Drilling and well services",
    details: "Details",
  },
  {
    id: 9,
    number: "09",
    code: "1755",
    name: "LEKOIL LIMITED",
    category: "Drilling and well services",
    details: "Details",
  },
];


export const managementData = [
  {
    id: 1,
    number: "01",
    code: "6465",
    name: "Anderson Okon",
    email:"aokon@neabidynmic.com",
    details: "Details",
  },
  {
    id: 2,
    number: "02",
    code: "5665",
    name: "Precious James",
    email:"aokon@neabidynmic.com",
    details: "Details",
  },
  {
    id: 3,
    number: "03",
    code: "1785",
    name: "Owolabi Akin",
    email:"aokon@neabidynmic.com",
    details: "Details",
  },
  {
    id: 4,
    number: "04",
    code: "6465",
    name: "Kabiru Usmah",
    email:"aokon@neabidynmic.com",
    details: "Details",
  },
  {
    id: 5,
    number: "05",
    code: "5665",
    name: "Emeka Igwe",
    email:"aokon@neabidynmic.com",
    details: "Details",
  },
  {
    id: 6,
    number: "06",
    code: "1755",
    name: "Ovunda Eze",
    email:"aokon@neabidynmic.com",
    details: "Details",
  },
  {
    id: 7,
    number: "07",
    code: "6465",
    name: "Segun Alabi",
    email:"aokon@neabidynmic.com",
    details: "Details",
  },
  {
    id: 8,
    number: "08",
    code: "5665",
    name: "Hassan Yusuf",
    email:"aokon@neabidynmic.com",
    details: "Details",
  },
  {
    id: 9,
    number: "09",
    code: "1755",
    name: "Mark Anthony",
    email:"aokon@neabidynmic.com",
    details: "Details",
  },
];
